export interface IStorage {
  get<T>(key: string): Promise<T | null>;
  set<T>(key: string, value: T): Promise<void>;
  delete(key: string): Promise<void>;
  query<T>(table: string, filter?: Record<string, unknown>): Promise<T[]>;
  insert<T>(table: string, record: T): Promise<string>; // returns ID
  update<T>(table: string, record: T): Promise<void>; // updates existing record (must have id)
}

export interface RitualLog {
  id: string;              // UUID
  ritualId: string;        // e.g., "morning-anchor"
  constellationId: string | null; // Optional constellation association
  completedAt: string;     // ISO timestamp
  durationSeconds: number; // Total time taken
  stepsCompleted: string[]; // Array of step IDs
}

export interface DopamineState {
  energy: number;
  xp: number;
  level: number;
  updatedAt: string;
}

export interface RitualStep {
  id: string;
  prompt: string;
  durationHint: number; // in seconds
}

export interface RitualDefinition {
  id: string;
  name: string;
  description: string;
  steps: RitualStep[];
}

// Constellation Types (Phase 3)
export interface ConstellationDefinition {
  id: string;              // e.g., "launch-saas"
  name: string;            // "Launch SaaS"
  description: string;     // Optional description
  color: string;           // Hex color for UI theming
  icon: string;            // Icon identifier
  createdAt: string;       // ISO timestamp
  archived: boolean;       // Default false
}

export interface SessionLog {
  id: string;              // UUID
  sessionId: string;       // Generated by SessionTimer
  constellationId: string | null; // Optional constellation association
  startedAt: string;       // ISO timestamp
  completedAt: string;     // ISO timestamp
  durationSeconds: number; // Actual time worked
  plannedDuration: number; // Original timer setting
  wasCompleted: boolean;   // True if full duration, false if abandoned
}

export interface ConstellationStats {
  constellationId: string;
  totalSessions: number;
  totalRituals: number;
  totalMinutes: number;
  lastActivityAt: string | null;
  completionRate: number; // % of sessions completed vs abandoned
}
